#!/usr/bin/env bash
# Generate deploy/gpu/.env for the machine with the GPU.
#
#   ./deploy/gpu/bootstrap-env.sh
#
# One value is born here — the token this host and its callers share. Where
# the catalog is does not go in this file at all: the service reads this
# machine's own config.toml (STRATA_CONFIG), the one the CLI uses, and trains
# from its default catalog. Pointing this host at another catalog is changing
# that default and restarting the service; nothing here needs regenerating.
#
# The rest are credentials this script has no business guessing. The S3 keys
# are left blank on purpose even though this machine probably has a working
# pair in its environment: those are the read-write ones, and this host reads
# samples and writes nothing to the bucket. Pasting the wrong key here would
# work, which is exactly why it is not done for you.
#
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo=$(cd "$here/../.." && pwd)
env_file="$here/.env"
config="$repo/config.toml"

if [ -e "$env_file" ]; then
    echo "$env_file already exists. Move it aside first if you mean to start over." >&2
    exit 1
fi
if [ ! -r "$config" ]; then
    echo "No $config. The service reads its catalog from it, as the CLI does." >&2
    exit 1
fi

token=$(openssl rand -hex 32)
modelling_root=${STRATA_MODELLING_ROOT:-$HOME/strata/modelling}
blobs_cache=${STRATA_BLOBS_CACHE:-$repo/catalog/blobs}
mkdir -p "$modelling_root"

umask 077
cat > "$env_file" <<EOF
# Generated by bootstrap-env.sh. Absolute paths throughout: systemd does not
# inherit a working directory, and mounting these at the same paths inside a
# container later leaves this file identical in both worlds.

STRATA_MODELLING_ROOT=$modelling_root
STRATA_BLOBS_CACHE=$blobs_cache

# Where the catalog is: this machine's config.toml, whose [catalog] default is
# the one trained from. Everything below is a credential.
STRATA_CONFIG=$config

# The index's password. config.toml names the index without one.
PGPASSWORD=${PGPASSWORD:-}

# Shared with whoever submits rounds. Put it in the password manager as
# 'strata-modelling-token' so the CLI can export it too.
STRATA_MODELLING_TOKEN=$token

# The READ-ONLY key. This host reads samples and writes nothing to the
# bucket, and a key that can write is a key that can destroy the corpus.
STRATA_S3_ACCESS_KEY=
STRATA_S3_SECRET_KEY=

STRATA_SERVE_HOST=0.0.0.0
STRATA_SERVE_PORT=8082
EOF
chmod 600 "$env_file"

echo "Wrote $env_file (0600)."
echo
echo "Still to fill in by hand:"
echo "  STRATA_S3_ACCESS_KEY / STRATA_S3_SECRET_KEY — the read-only Garage key"
if [ -z "${PGPASSWORD:-}" ]; then
    echo "  PGPASSWORD — the index's password; source scripts/secrets.sh and redo, or paste it"
fi
echo
echo "Then:"
echo "  cp $here/strata-modelling.service ~/.config/systemd/user/"
echo "  systemctl --user daemon-reload && systemctl --user enable --now strata-modelling"
echo "  sudo loginctl enable-linger \$USER"
echo
echo "The token also belongs in the password manager, for the CLI to export:"
echo "  grep STRATA_MODELLING_TOKEN $env_file"
