#!/usr/bin/env bash
# Generate deploy/gpu/.env for the machine with the GPU.
#
#   ./deploy/gpu/bootstrap-env.sh
#
# One value is born here — the token this host and its callers share. The
# rest is either already in config.toml (where the index and the bucket are)
# or is a credential this script has no business guessing.
#
# The S3 keys are left blank on purpose even though this machine probably
# has a working pair in its environment: those are the read-write ones, and
# this host reads samples and writes nothing to the bucket. Pasting the
# wrong key here would work, which is exactly why it is not done for you.
#
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo=$(cd "$here/../.." && pwd)
env_file="$here/.env"
config="$repo/config.toml"

if [ -e "$env_file" ]; then
    echo "$env_file already exists. Move it aside first if you mean to start over." >&2
    exit 1
fi
if [ ! -r "$config" ]; then
    echo "No $config to read the index and bucket from." >&2
    exit 1
fi

# Straight out of the config this machine already uses, so the service and
# the CLI cannot drift apart on where the catalog is.
catalog_url=$(grep -oE 'postgresql\+psycopg://[^"]+' "$config" | head -1 || true)
s3_endpoint=$(sed -nE 's/^s3_endpoint[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' "$config" | head -1)
s3_bucket=$(sed -nE 's/^s3_bucket[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' "$config" | head -1)

if [ -z "$catalog_url" ]; then
    echo "No postgres URL in $config — set [catalog] url first." >&2
    exit 1
fi

# config.toml deliberately holds no password; $PGPASSWORD supplies it. The
# service reads a single URL, so the two halves are joined here.
# Only the userinfo decides, not the whole string: every one of these URLs
# has a colon in its scheme, so testing the lot finds a password that is not
# there and skips the join in silence.
authority=${catalog_url#*://}
userinfo=""
[[ "$authority" == *@* ]] && userinfo=${authority%%@*}

if [[ "$userinfo" != *:* ]]; then
    if [ -n "${PGPASSWORD:-}" ]; then
        catalog_url=$(printf '%s' "$catalog_url" |
            sed -E "s|://([^@/]+)@|://\1:${PGPASSWORD}@|")
    else
        echo "No password in the URL and \$PGPASSWORD is unset — leaving CHANGEME." >&2
        catalog_url=$(printf '%s' "$catalog_url" | sed -E 's|://([^@/]+)@|://\1:CHANGEME@|')
    fi
fi

token=$(openssl rand -hex 32)
modelling_root=${STRATA_MODELLING_ROOT:-$HOME/strata/modelling}
blobs_cache=${STRATA_BLOBS_CACHE:-$repo/catalog/blobs}
mkdir -p "$modelling_root"

umask 077
cat > "$env_file" <<EOF
# Generated by bootstrap-env.sh. Absolute paths throughout: systemd does not
# inherit a working directory, and mounting these at the same paths inside a
# container later leaves this file identical in both worlds.

STRATA_MODELLING_ROOT=$modelling_root
STRATA_BLOBS_CACHE=$blobs_cache

STRATA_CATALOG_URL=$catalog_url

# Shared with whoever submits rounds. Put it in the password manager as
# 'strata-modelling-token' so the CLI can export it too.
STRATA_MODELLING_TOKEN=$token

# The READ-ONLY key. This host reads samples and writes nothing to the
# bucket, and a key that can write is a key that can destroy the corpus.
STRATA_S3_ENDPOINT=$s3_endpoint
STRATA_S3_BUCKET=$s3_bucket
STRATA_S3_ACCESS_KEY=
STRATA_S3_SECRET_KEY=

STRATA_SERVE_HOST=0.0.0.0
STRATA_SERVE_PORT=8082
EOF
chmod 600 "$env_file"

echo "Wrote $env_file (0600)."
echo
echo "Still to fill in by hand:"
echo "  STRATA_S3_ACCESS_KEY / STRATA_S3_SECRET_KEY — the read-only Garage key"
case "$catalog_url" in
    *CHANGEME*) echo "  STRATA_CATALOG_URL — no password; source scripts/secrets.sh and redo, or paste it" ;;
esac
echo
echo "Then:"
echo "  cp $here/strata-modelling.service ~/.config/systemd/user/"
echo "  systemctl --user daemon-reload && systemctl --user enable --now strata-modelling"
echo "  sudo loginctl enable-linger \$USER"
echo
echo "The token also belongs in the password manager, for the CLI to export:"
echo "  grep STRATA_MODELLING_TOKEN $env_file"
